build:
	nvcc --std=c++11 -g -G example01.cu -Iinclude -o example01
	nvcc --std=c++11 -g -G example02.cu -Iinclude -o example02
	nvcc --std=c++11 -g -G example03.cu -Iinclude -o example03
	nvcc --std=c++11 -g -G example04.cu -Iinclude -o example04